version: '3'

services:
  springboot-api-db:
    image: mysql:8.0.32
    container_name: springboot-api-db
    ports:
      - "3306:3306"
    volumes:
      - springboot_api_mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=springboot
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - springboot-api-network

  springboot-api:
    container_name: springboot-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - springboot-api-network
    depends_on:
      - springboot-api-db

volumes:
  springboot_api_mysql:
    driver: local

networks:
  springboot-api-network:
    driver: bridge
