apiVersion: v1
kind: Namespace
metadata:
  name: springboot-api
spec:
  finalizers:
    - kubernetes

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-mysql
  name: springboot-mysql
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3306
    nodePort: 32222
    protocol: TCP
    targetPort: 3306
  type: NodePort
  selector:
    app: springboot-mysql

---


